# Generated by Codex on 2026-05-22

from django.db import migrations, models


def migrate_roles(apps, _schema_editor):
    UserProfile = apps.get_model("sightline", "UserProfile")
    UserProfile.objects.filter(role__in=["operator", "faculty", "department_head"]).update(role="teacher")


class Migration(migrations.Migration):

    dependencies = [
        ("sightline", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("invigilator", "Invigilator"),
                    ("student", "Student"),
                ],
                max_length=32,
            ),
        ),
    ]
