# Generated by Django 5.1.3 on 2026-05-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sightline", "0003_course_teacher_examvideo_courseenrollment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsession",
            name="quiz_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="examsession",
            name="quiz_questions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="examsession",
            name="quiz_title",
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
