# Generated by Django 5.1.3 on 2026-05-24 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sightline", "0005_course_materials"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertevent",
            name="exam_video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="sightline.examvideo",
            ),
        ),
        migrations.AddField(
            model_name="examvideo",
            name="analysis_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="examvideo",
            name="analysis_report",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="examvideo",
            name="analysis_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="examvideo",
            name="duration_seconds",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="examvideo",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="examvideo",
            name="frames_analyzed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="evidenceasset",
            name="uri",
            field=models.CharField(max_length=300),
        ),
    ]
