# Generated by Django 5.2.16 on 2026-07-09 18:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightline', '0010_alter_coursematerial_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessmentrun',
            name='feature_importance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='riskassessmentrun',
            name='model_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='previous_gpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='studentriskscore',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='FacultyActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('auto_email', 'Automatic email'), ('email', 'Email'), ('meeting', 'Meeting'), ('call', 'Call'), ('note', 'Note')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sightline.course')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_actions', to=settings.AUTH_USER_MODEL)),
                ('risk_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='sightline.studentriskscore')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_actions', to='sightline.studentprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ScheduledSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('class', 'Class'), ('exam', 'Exam')], default='class', max_length=16)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sessions', to='sightline.course')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_sessions', to='sightline.hall')),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilating_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('starts_at', 'id'),
            },
        ),
    ]
